from __future__ import annotations

from pathlib import Path
from typing import Any

from osteo_vision_core.reports.writers import write_csv

QUANTIFICATION_FIELDS = [
    "case_id",
    "run_id",
    "roi_id",
    "threshold",
    "mean_intensity",
    "max_intensity",
    "p95_intensity",
    "positive_area_px",
    "positive_area_fraction",
    "review_state",
    "record_type",
    "frame_index",
    "timestamp_sec",
    "activity_class",
    "activity_label",
    "bone_gate_fraction",
    "activity_mask_sha256",
    "activity_sources",
    "activity_status",
    "calibration_status",
    "spatial_effect_applied",
    "review_required",
    "confidence_boundary",
    "medical_boundary",
    "clinical_context_revision",
    "clinical_context_checksum",
    "clinical_context_quality_status",
    "clinical_calibration_applied",
    "clinical_calibration_status",
    "clinical_spatial_effect_applied",
    "patient_conditioned_model_id",
    "patient_conditioning_available",
    "patient_conditioning_proxy_checkpoint",
    "patient_conditioning_safe_fallback",
    "patient_conditioning_target_domain_promotion_ready",
    "patient_conditioning_runtime_replacement_allowed",
    "patient_conditioning_feature_present_fraction",
    "patient_conditioning_difference_area_px",
    "patient_conditioning_spatial_effect_area_px",
    "patient_conditioning_delta_abs_mean",
    "patient_conditioning_uncertainty_mean",
    "patient_conditioning_failure_reasons",
    "patient_conditioning_reviewed_bone_gate_sha256",
    "patient_conditioning_evidence_manifest_path",
    "clinical_feature_vector_schema_version",
    "clinical_feature_vector_feature_version",
    "clinical_feature_vector_feature_names",
    "clinical_feature_vector_present_mask",
    "clinical_feature_vector_missing_mask",
    "clinical_feature_vector_ood_mask",
    "clinical_feature_vector_checkpoint_consumed_mask",
    "clinical_feature_vector_spatial_effect_applied_mask",
    "clinical_feature_vector_recorded_input_summary",
    "clinical_feature_vector_checkpoint_consumed_feature_names",
    "clinical_feature_vector_spatially_applied_feature_names",
    "clinical_feature_vector_missing_feature_names",
    "clinical_feature_vector_ood_feature_names",
    "clinical_feature_vector_unconsumed_recorded_inputs",
    "clinical_feature_vector_vector_checksum",
    "clinical_feature_vector_runtime_vector_checksum",
    "bone_activity_evidence_type",
    "bone_activity_model_id",
    "bone_activity_model_family",
    "bone_activity_input_domain",
    "bone_activity_execution_state",
    "bone_activity_engineering_inference_executed",
    "bone_activity_proxy_checkpoint",
    "bone_activity_engineering_ready",
    "bone_activity_engineering_utility_ready",
    "bone_activity_spatial_candidates_available",
    "bone_activity_spatial_effect_applied",
    "bone_activity_safe_fallback_applied",
    "bone_activity_target_domain_promotion_ready",
    "bone_activity_runtime_replacement_allowed",
    "bone_activity_checkpoint_sha256",
    "bone_activity_manifest_sha256",
    "bone_activity_raw_engineering_outputs_path",
    "bone_activity_raw_engineering_outputs_sha256",
    "bone_activity_raw_spatial_use_allowed",
    "bone_activity_evidence_manifest_path",
    "bone_activity_evidence_manifest_sha256",
    "bone_activity_registration_verified",
    "bone_activity_reviewed_bone_gate_status",
    "bone_activity_target_domain_input_verified",
    "bone_activity_failure_reasons",
]


def write_quantification_csv(path: str | Path, rows: list[dict[str, Any]]) -> str:
    return write_csv(path, rows, QUANTIFICATION_FIELDS)
